//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRessources.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReAbonnement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReAbonnement() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppRessources.Ressources.ReAbonnement", typeof(ReAbonnement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ adresse ne doit pas être vide!.
        /// </summary>
        public static string adresseClientNonVide {
            get {
                return ResourceManager.GetString("adresseClientNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ adresse organisme ne doit pas être vide!.
        /// </summary>
        public static string adresseOrganismeNonVide {
            get {
                return ResourceManager.GetString("adresseOrganismeNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ adresse de la responsable de l&apos;organisme ne doit pas être vide!.
        /// </summary>
        public static string adresseRespOrganisme {
            get {
                return ResourceManager.GetString("adresseRespOrganisme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ adresse de la responsable de la société ne doit pas être vide!.
        /// </summary>
        public static string adresseRespSocieteNonVide {
            get {
                return ResourceManager.GetString("adresseRespSocieteNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ adresse société ne doit pas être vide!.
        /// </summary>
        public static string adresseSocieteNonVide {
            get {
                return ResourceManager.GetString("adresseSocieteNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ prénom ne doit pas être vide!.
        /// </summary>
        public static string cinClientNonVide {
            get {
                return ResourceManager.GetString("cinClientNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ CIN de la responsable de l&apos;organisme ne doit pas être vide!.
        /// </summary>
        public static string cinRespOrganisme {
            get {
                return ResourceManager.GetString("cinRespOrganisme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ CIN de la responsable de la société ne doit pas être vide!.
        /// </summary>
        public static string cinRespSocieteNonVide {
            get {
                return ResourceManager.GetString("cinRespSocieteNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ date ne doit pas être vide!.
        /// </summary>
        public static string dateNonVide {
            get {
                return ResourceManager.GetString("dateNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur ce produit durant l&apos;enregistrement!.
        /// </summary>
        public static string erreurPendantEnregistrement {
            get {
                return ResourceManager.GetString("erreurPendantEnregistrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur du champ mail organisme est non valide!.
        /// </summary>
        public static string mailOrganismeNonValide {
            get {
                return ResourceManager.GetString("mailOrganismeNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur du champ mail de la responsable organime est non valide!.
        /// </summary>
        public static string mailRespOrganismeNonValide {
            get {
                return ResourceManager.GetString("mailRespOrganismeNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur du champ mail de la responsable société est non valide!.
        /// </summary>
        public static string mailResSocieteNonValide {
            get {
                return ResourceManager.GetString("mailResSocieteNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur du champ mail société est non valide!.
        /// </summary>
        public static string mailSocieteNonValide {
            get {
                return ResourceManager.GetString("mailSocieteNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nombre ne doit pas être vide!.
        /// </summary>
        public static string nombreNonVide {
            get {
                return ResourceManager.GetString("nombreNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ non ne doit pas être vide!.
        /// </summary>
        public static string nomClientNonVide {
            get {
                return ResourceManager.GetString("nomClientNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nom organisme ne doit pas être vide!.
        /// </summary>
        public static string nomOrganismeNonVide {
            get {
                return ResourceManager.GetString("nomOrganismeNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nom de la responsable de l&apos;organisme ne doit pas être vide!.
        /// </summary>
        public static string nomRespOrganisme {
            get {
                return ResourceManager.GetString("nomRespOrganisme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ non de la responsable de la société ne doit pas être vide!.
        /// </summary>
        public static string nomRespSocieteNonVide {
            get {
                return ResourceManager.GetString("nomRespSocieteNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nom société ne doit pas être vide!.
        /// </summary>
        public static string nomSocieteNonVide {
            get {
                return ResourceManager.GetString("nomSocieteNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ prix ne doit pas être vide!.
        /// </summary>
        public static string prixBilltNonVide {
            get {
                return ResourceManager.GetString("prixBilltNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ secteur d&apos;activité ne doit pas être vide!.
        /// </summary>
        public static string secteurSocieteNonVide {
            get {
                return ResourceManager.GetString("secteurSocieteNonVide", resourceCulture);
            }
        }
    }
}
