//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRessources.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReBilletCommissionDevis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReBilletCommissionDevis() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppRessources.Ressources.ReBilletCommissionDevis", typeof(ReBilletCommissionDevis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ catégorie ne doit pas être vide!.
        /// </summary>
        public static string billetCategorieNonVide {
            get {
                return ResourceManager.GetString("billetCategorieNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nombre billet ne doit pas être vide!.
        /// </summary>
        public static string billetNombreNonVide {
            get {
                return ResourceManager.GetString("billetNombreNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ prix billet ne doit pas être vide!.
        /// </summary>
        public static string billetPrixNonVide {
            get {
                return ResourceManager.GetString("billetPrixNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ prix total ne doit pas être vide!.
        /// </summary>
        public static string billetPrixTotalNonVide {
            get {
                return ResourceManager.GetString("billetPrixTotalNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ ville départ ne doit pas être vide!.
        /// </summary>
        public static string billetVilleDepartNonVide {
            get {
                return ResourceManager.GetString("billetVilleDepartNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ ville destination ne doit pas être vide!.
        /// </summary>
        public static string billetVilleDestinationNonVide {
            get {
                return ResourceManager.GetString("billetVilleDestinationNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ adresse client ne doit pas être vide!.
        /// </summary>
        public static string clientAdresseNonVide {
            get {
                return ResourceManager.GetString("clientAdresseNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ CIN client ne doit pas être vide!.
        /// </summary>
        public static string clientCINNonVide {
            get {
                return ResourceManager.GetString("clientCINNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nom client ne doit pas être vide!.
        /// </summary>
        public static string clientNomNonVide {
            get {
                return ResourceManager.GetString("clientNomNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ frais d&apos;envoi ne doit pas être vide!.
        /// </summary>
        public static string commissionFraisNonVide {
            get {
                return ResourceManager.GetString("commissionFraisNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nombre commission ne doit pas être vide!.
        /// </summary>
        public static string commissionNombreNonVide {
            get {
                return ResourceManager.GetString("commissionNombreNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ pièce justificatif ne doit pas être vide!.
        /// </summary>
        public static string commissionPieceJustificatifNonVide {
            get {
                return ResourceManager.GetString("commissionPieceJustificatifNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ poids commission ne doit pas être vide!.
        /// </summary>
        public static string commissionPoidsNonVide {
            get {
                return ResourceManager.GetString("commissionPoidsNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ CIN expéditeur ne doit pas être vide!.
        /// </summary>
        public static string expediteurCINNonVide {
            get {
                return ResourceManager.GetString("expediteurCINNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nom expéditeur ne doit pas être vide!.
        /// </summary>
        public static string expediteurNomNonVide {
            get {
                return ResourceManager.GetString("expediteurNomNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ adresse individu ne doit pas être vide!.
        /// </summary>
        public static string individuAdresseNonVide {
            get {
                return ResourceManager.GetString("individuAdresseNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ CIN individu ne doit pas être vide.
        /// </summary>
        public static string individuCINNonVide {
            get {
                return ResourceManager.GetString("individuCINNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nom individu ne doit pas être vide!.
        /// </summary>
        public static string individuNomNonVide {
            get {
                return ResourceManager.GetString("individuNomNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nombre de billet ne doit pas être vide!.
        /// </summary>
        public static string nbBilletNonVide {
            get {
                return ResourceManager.GetString("nbBilletNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ adresse organisme ne doit pas être vide!.
        /// </summary>
        public static string organismeAdresseNonVide {
            get {
                return ResourceManager.GetString("organismeAdresseNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ adesse responsable organisme ne doit pas être vide!.
        /// </summary>
        public static string organismeAdresseRespNonVide {
            get {
                return ResourceManager.GetString("organismeAdresseRespNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ CIN responsable organisme ne doit pas être vide!.
        /// </summary>
        public static string organismeCINRespNonVide {
            get {
                return ResourceManager.GetString("organismeCINRespNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ mail organisme non valide!.
        /// </summary>
        public static string organismeMailNonValide {
            get {
                return ResourceManager.GetString("organismeMailNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ mail responsable organisme non valide!.
        /// </summary>
        public static string organismeMailRespNonVide {
            get {
                return ResourceManager.GetString("organismeMailRespNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ non organisme vide!.
        /// </summary>
        public static string organismeNonNonVide {
            get {
                return ResourceManager.GetString("organismeNonNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nom responsable organisme ne doit pas être vide!.
        /// </summary>
        public static string organismeNonRespNonVide {
            get {
                return ResourceManager.GetString("organismeNonRespNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nom récéptionnaire ne doit pas être vide!.
        /// </summary>
        public static string receptionnaireNomNonVide {
            get {
                return ResourceManager.GetString("receptionnaireNomNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ adresse société ne doit pas être vide!.
        /// </summary>
        public static string societeAdresseNonVide {
            get {
                return ResourceManager.GetString("societeAdresseNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ adresse responsable ne doit pas être vide!.
        /// </summary>
        public static string societeAdresseResponsableNonVide {
            get {
                return ResourceManager.GetString("societeAdresseResponsableNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ CIN responsable société ne doit pas être vide!.
        /// </summary>
        public static string societeCINRespNonVide {
            get {
                return ResourceManager.GetString("societeCINRespNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ mail société n&apos;est pas valide!.
        /// </summary>
        public static string societeMailNonValide {
            get {
                return ResourceManager.GetString("societeMailNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ mail responsable société non valide!.
        /// </summary>
        public static string societeMailResponsableNonValide {
            get {
                return ResourceManager.GetString("societeMailResponsableNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nom société ne doit pas être vide!.
        /// </summary>
        public static string societeNomNonVide {
            get {
                return ResourceManager.GetString("societeNomNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nom responsable société ne doit pas être vide!.
        /// </summary>
        public static string societeNomResponsableNonVide {
            get {
                return ResourceManager.GetString("societeNomResponsableNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ secteur d&apos;activité ne doit pas ête vide!.
        /// </summary>
        public static string societeSecteurNonVide {
            get {
                return ResourceManager.GetString("societeSecteurNonVide", resourceCulture);
            }
        }
    }
}
