//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRessources.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReCheque {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReCheque() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppRessources.Ressources.ReCheque", typeof(ReCheque).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ adresse titulaire ne doit pas être vide!.
        /// </summary>
        public static string adresseTitulaireNonVide {
            get {
                return ResourceManager.GetString("adresseTitulaireNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ banque ne doit pas être vide!.
        /// </summary>
        public static string banqueNonVide {
            get {
                return ResourceManager.GetString("banqueNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ date chèque ne doit pas être vide!.
        /// </summary>
        public static string dateChequeNonVide {
            get {
                return ResourceManager.GetString("dateChequeNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ description chèque ne doit pas être vide!.
        /// </summary>
        public static string descriptionChequeNonVide {
            get {
                return ResourceManager.GetString("descriptionChequeNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur ce produit durant l&apos;enregistrement!.
        /// </summary>
        public static string erreurPendantInsertion {
            get {
                return ResourceManager.GetString("erreurPendantInsertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification non enregistrer!.
        /// </summary>
        public static string modificationNonEnregistrer {
            get {
                return ResourceManager.GetString("modificationNonEnregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ montant chèque ne doit pas être vide!.
        /// </summary>
        public static string montantChequeNonVide {
            get {
                return ResourceManager.GetString("montantChequeNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ numeros de compte ne doit pas être vide!.
        /// </summary>
        public static string numComptNonVide {
            get {
                return ResourceManager.GetString("numComptNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ numeros chèque ne doit pas être vide!.
        /// </summary>
        public static string numerosChequeNonVide {
            get {
                return ResourceManager.GetString("numerosChequeNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veillez séléctionné un chèque!.
        /// </summary>
        public static string selectionnerUnCheque {
            get {
                return ResourceManager.GetString("selectionnerUnCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ titulaire ne doit pas être vide!.
        /// </summary>
        public static string titulaireNonVide {
            get {
                return ResourceManager.GetString("titulaireNonVide", resourceCulture);
            }
        }
    }
}
