//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRessources.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReChauffeur {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReChauffeur() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppRessources.Ressources.ReChauffeur", typeof(ReChauffeur).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ adresse ne doit pas être vide!.
        /// </summary>
        public static string adresseNonVide {
            get {
                return ResourceManager.GetString("adresseNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ CIN ne doit pas être vide!.
        /// </summary>
        public static string cinNonVide {
            get {
                return ResourceManager.GetString("cinNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce CIN existe déjà dans la base, veiller verifier s&apos;il vous plais!.
        /// </summary>
        public static string FormulaireExistant {
            get {
                return ResourceManager.GetString("FormulaireExistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrement non effectuer!.
        /// </summary>
        public static string InsertionNonValide {
            get {
                return ResourceManager.GetString("InsertionNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur ce produit durant la sélection, veiller resélectionner s\&apos;il vous plais!.
        /// </summary>
        public static string jsErreureAffichage {
            get {
                return ResourceManager.GetString("jsErreureAffichage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur ce produit durant la sélection,\n veiller resélectionner s\&apos;il vous plais!.
        /// </summary>
        public static string JsErreurObjet {
            get {
                return ResourceManager.GetString("JsErreurObjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrement du chauffeur avec succès!.
        /// </summary>
        public static string jsInsertionOk {
            get {
                return ResourceManager.GetString("jsInsertionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification effectuer!.
        /// </summary>
        public static string jsModificationEnregistrer {
            get {
                return ResourceManager.GetString("jsModificationEnregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppresion du chauffeur avec succés!.
        /// </summary>
        public static string jsSuppresionEnregistre {
            get {
                return ResourceManager.GetString("jsSuppresionEnregistre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification non effectuer!.
        /// </summary>
        public static string ModiffierNonEnregistre {
            get {
                return ResourceManager.GetString("ModiffierNonEnregistre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veiller sélectionner avant de modifier!.
        /// </summary>
        public static string ModificationNonAutorise {
            get {
                return ResourceManager.GetString("ModificationNonAutorise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nom ne doit pas être vide!.
        /// </summary>
        public static string nomNonVide {
            get {
                return ResourceManager.GetString("nomNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ situation familiale ne doit pas être vide!.
        /// </summary>
        public static string situationFamilialeNonVide {
            get {
                return ResourceManager.GetString("situationFamilialeNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veiller sélectionner avant de supprimer!.
        /// </summary>
        public static string SuppressionNonAutorise {
            get {
                return ResourceManager.GetString("SuppressionNonAutorise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression non effectuer!.
        /// </summary>
        public static string SuppressionNonEnregistre {
            get {
                return ResourceManager.GetString("SuppressionNonEnregistre", resourceCulture);
            }
        }
    }
}
