//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRessources.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReCreditAbonnement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReCreditAbonnement() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppRessources.Ressources.ReCreditAbonnement", typeof(ReCreditAbonnement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ adresse titulaire ne doit pas être vide!.
        /// </summary>
        public static string adresseTitulaireNonVide {
            get {
                return ResourceManager.GetString("adresseTitulaireNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ banque ne doit pas être vide!.
        /// </summary>
        public static string banqueNonVide {
            get {
                return ResourceManager.GetString("banqueNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ date au ne doit pas êrte vide!.
        /// </summary>
        public static string dateAuNonVide {
            get {
                return ResourceManager.GetString("dateAuNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ date chèque ne doit pas être vide!.
        /// </summary>
        public static string dateChequeNonVide {
            get {
                return ResourceManager.GetString("dateChequeNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ date du ne doit pas être vide!.
        /// </summary>
        public static string dateDuNonVide {
            get {
                return ResourceManager.GetString("dateDuNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mode de paiement non sélectionné!.
        /// </summary>
        public static string modePaiementNonVide {
            get {
                return ResourceManager.GetString("modePaiementNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ montant ne doit pas être vide!.
        /// </summary>
        public static string montantChequeNonVide {
            get {
                return ResourceManager.GetString("montantChequeNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nombre de voyage ne doit pas être vide!.
        /// </summary>
        public static string nombreVoyageNonVide {
            get {
                return ResourceManager.GetString("nombreVoyageNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ référence chèque ne doit pas être vide!.
        /// </summary>
        public static string numChequeNonVide {
            get {
                return ResourceManager.GetString("numChequeNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ numeros chèque ne doit pas être vide!.
        /// </summary>
        public static string numerosChequeNonVide {
            get {
                return ResourceManager.GetString("numerosChequeNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ numeros de compte ne doit pas être vide!.
        /// </summary>
        public static string numerosCompteNonVide {
            get {
                return ResourceManager.GetString("numerosCompteNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ prix  total ne doit pas être vide!.
        /// </summary>
        public static string prixTotalDANonVide {
            get {
                return ResourceManager.GetString("prixTotalDANonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ prix  total ne doit pas être vide!.
        /// </summary>
        public static string prixTotalVANonVide {
            get {
                return ResourceManager.GetString("prixTotalVANonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ prix unitaire ne doit pas être vide!.
        /// </summary>
        public static string prixUnitaireRNNonVide {
            get {
                return ResourceManager.GetString("prixUnitaireRNNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ prix unitaire ne doit pas être vide!.
        /// </summary>
        public static string prixUnitaireSUNonVide {
            get {
                return ResourceManager.GetString("prixUnitaireSUNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ titulaire ne doit pas être vide!.
        /// </summary>
        public static string titulaireNonVide {
            get {
                return ResourceManager.GetString("titulaireNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type abonnement non sélectionné!.
        /// </summary>
        public static string typeAbonnementNonVide {
            get {
                return ResourceManager.GetString("typeAbonnementNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zone non sélectionnée!.
        /// </summary>
        public static string zoneNonVide {
            get {
                return ResourceManager.GetString("zoneNonVide", resourceCulture);
            }
        }
    }
}
