//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRessources.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReGareRoutiere {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReGareRoutiere() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppRessources.Ressources.ReGareRoutiere", typeof(ReGareRoutiere).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce sigle existe déjà dans la base, veiller verifier s&apos;il vous plais!.
        /// </summary>
        public static string FormulaireExistant {
            get {
                return ResourceManager.GetString("FormulaireExistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string FormulaireVide {
            get {
                return ResourceManager.GetString("FormulaireVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrement non effectuer!.
        /// </summary>
        public static string InsertionNonValide {
            get {
                return ResourceManager.GetString("InsertionNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur ce produit durant la sélection, veiller resélectionner s\&apos;il vous plais!.
        /// </summary>
        public static string jsErreurAffichage {
            get {
                return ResourceManager.GetString("jsErreurAffichage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur ce produit durant la sélection,\n veiller resélectionner s\&apos;il vous plais!.
        /// </summary>
        public static string jsErreurObjet {
            get {
                return ResourceManager.GetString("jsErreurObjet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insertion de la gare routière avec succès!.
        /// </summary>
        public static string jsInsertionValide {
            get {
                return ResourceManager.GetString("jsInsertionValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification de la gare routière avec succés!.
        /// </summary>
        public static string jsModificationValide {
            get {
                return ResourceManager.GetString("jsModificationValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression de la gare routière avec succés!.
        /// </summary>
        public static string JsSuppressionBienEnregistrer {
            get {
                return ResourceManager.GetString("JsSuppressionBienEnregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veiller sélectionner avant de modifier!.
        /// </summary>
        public static string ModiffierNonAutoriser {
            get {
                return ResourceManager.GetString("ModiffierNonAutoriser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification non effectuer!.
        /// </summary>
        public static string ModiffierNonEnregistre {
            get {
                return ResourceManager.GetString("ModiffierNonEnregistre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veiller sélectionner avant de supprimer!.
        /// </summary>
        public static string SupprimerNonAutorise {
            get {
                return ResourceManager.GetString("SupprimerNonAutorise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression non effectuer!.
        /// </summary>
        public static string SupprimerNonEnregistre {
            get {
                return ResourceManager.GetString("SupprimerNonEnregistre", resourceCulture);
            }
        }
    }
}
