//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRessources.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReRecuCommission {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReRecuCommission() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppRessources.Ressources.ReRecuCommission", typeof(ReRecuCommission).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ CIN expediteur ne doit pas être vide!.
        /// </summary>
        public static string cinExpediteurNonVide {
            get {
                return ResourceManager.GetString("cinExpediteurNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ frais de commission ne doit pas être vide!.
        /// </summary>
        public static string fraisNonVide {
            get {
                return ResourceManager.GetString("fraisNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nombre de commission ne doit pas être vide!.
        /// </summary>
        public static string nombreCommissionNonVide {
            get {
                return ResourceManager.GetString("nombreCommissionNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nom expediteur ne doit pas être vide!.
        /// </summary>
        public static string nomExpediteurNonVide {
            get {
                return ResourceManager.GetString("nomExpediteurNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nom réceptionnaire ne doit pas être vide!.
        /// </summary>
        public static string nomRecepteurNonVide {
            get {
                return ResourceManager.GetString("nomRecepteurNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ pièce justificatif ne doit pas ête vide!.
        /// </summary>
        public static string pieceJustificatifNonVide {
            get {
                return ResourceManager.GetString("pieceJustificatifNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ poid de commission ne doit pas être vide!.
        /// </summary>
        public static string poidCommissionNonVide {
            get {
                return ResourceManager.GetString("poidCommissionNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le reçu est bien enregistré!.
        /// </summary>
        public static string recuCommissionEnregistre {
            get {
                return ResourceManager.GetString("recuCommissionEnregistre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur ce produit durant l&apos;enregistrement du reçu!.
        /// </summary>
        public static string recuCommissionNonEnregistre {
            get {
                return ResourceManager.GetString("recuCommissionNonEnregistre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veiller resélectionner les deux villes s&apos;il vous plaît!.
        /// </summary>
        public static string trajetNonVide {
            get {
                return ResourceManager.GetString("trajetNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ ville de depart ne doit pas être vide!.
        /// </summary>
        public static string villeDepartNonVide {
            get {
                return ResourceManager.GetString("villeDepartNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ destination ne doit pas être vide!.
        /// </summary>
        public static string villeDestinationNonVide {
            get {
                return ResourceManager.GetString("villeDestinationNonVide", resourceCulture);
            }
        }
    }
}
