//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRessources.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReSociete {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReSociete() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppRessources.Ressources.ReSociete", typeof(ReSociete).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ adresse responsable société ne doit pas être vide!.
        /// </summary>
        public static string adresseResponsableSocieteNonVide {
            get {
                return ResourceManager.GetString("adresseResponsableSocieteNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ adresse société ne doit pas être vide! .
        /// </summary>
        public static string adresseSocieteNonVide {
            get {
                return ResourceManager.GetString("adresseSocieteNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ CIN responsable ne doit pas être vide!.
        /// </summary>
        public static string cinResponsableSocieteNonVide {
            get {
                return ResourceManager.GetString("cinResponsableSocieteNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification impossible!.
        /// </summary>
        public static string editionImpossible {
            get {
                return ResourceManager.GetString("editionImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur ce produit durant l&apos;insertion!.
        /// </summary>
        public static string erreurInsertion {
            get {
                return ResourceManager.GetString("erreurInsertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur du champ mail responsable société non valide!.
        /// </summary>
        public static string mailResponsableSocieteNonVide {
            get {
                return ResourceManager.GetString("mailResponsableSocieteNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La valeur du champ mail société non valide!.
        /// </summary>
        public static string mailSocieteNonValide {
            get {
                return ResourceManager.GetString("mailSocieteNonValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nom responsable société ne doit pas être vide!.
        /// </summary>
        public static string nomResponsableNonVide {
            get {
                return ResourceManager.GetString("nomResponsableNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nom société ne doit pas être vide!.
        /// </summary>
        public static string nomSocieteNonVide {
            get {
                return ResourceManager.GetString("nomSocieteNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ secteur d&apos;activité ne doit pas être vide!.
        /// </summary>
        public static string secteurNonVide {
            get {
                return ResourceManager.GetString("secteurNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veillez sélectionné une société!.
        /// </summary>
        public static string selectionneUneSociete {
            get {
                return ResourceManager.GetString("selectionneUneSociete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression impossible!.
        /// </summary>
        public static string suppressionImpossible {
            get {
                return ResourceManager.GetString("suppressionImpossible", resourceCulture);
            }
        }
    }
}
