//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRessources.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReVehiculeParametre {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReVehiculeParametre() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppRessources.Ressources.ReVehiculeParametre", typeof(ReVehiculeParametre).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ adresse chauffeur ne doit pas être vide!.
        /// </summary>
        public static string adresseChauffeurNonVide {
            get {
                return ResourceManager.GetString("adresseChauffeurNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ avance sur carburant maximum ne doit pas être vide!.
        /// </summary>
        public static string avanceCarburantNonVide {
            get {
                return ResourceManager.GetString("avanceCarburantNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ avance pour chauffeur maximum ne doit pas être vide!.
        /// </summary>
        public static string avanceChauffeurNonVide {
            get {
                return ResourceManager.GetString("avanceChauffeurNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ CIN chauffeur ne doit pas être vide!.
        /// </summary>
        public static string cinChauffeurNonVide {
            get {
                return ResourceManager.GetString("cinChauffeurNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ cooperative ne doit pas être vide.
        /// </summary>
        public static string cooperativeNonVide {
            get {
                return ResourceManager.GetString("cooperativeNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ date de mise en circulation ne doit pas être vide!.
        /// </summary>
        public static string dateMiseEnCirculationNonVide {
            get {
                return ResourceManager.GetString("dateMiseEnCirculationNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ date de première exploitation ne doit pas être vide!.
        /// </summary>
        public static string datePremiereExploitationNoNVide {
            get {
                return ResourceManager.GetString("datePremiereExploitationNoNVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ date valide au ne doit pas être vide!.
        /// </summary>
        public static string dateValideAuNonVide {
            get {
                return ResourceManager.GetString("dateValideAuNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ date valide du ne doit pas être vide!.
        /// </summary>
        public static string dateValideDuNonVide {
            get {
                return ResourceManager.GetString("dateValideDuNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ fond ne doit pas être vide!.
        /// </summary>
        public static string fondNonVide {
            get {
                return ResourceManager.GetString("fondNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ itinéraire 1 ne doit pas être vide!.
        /// </summary>
        public static string itineraireNonVide {
            get {
                return ResourceManager.GetString("itineraireNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ marque véhicule ne doit pas être vide!.
        /// </summary>
        public static string marqueVehiculeNonVide {
            get {
                return ResourceManager.GetString("marqueVehiculeNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ matricule doit être de la forme 9999 TAA ou 9999 TA.
        /// </summary>
        public static string matriculeForme {
            get {
                return ResourceManager.GetString("matriculeForme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ matricule véhicule ne doit pas être vide!.
        /// </summary>
        public static string matriculeVehiculeNonVide {
            get {
                return ResourceManager.GetString("matriculeVehiculeNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nombre de colonne véhicule ne doit pas être vide!.
        /// </summary>
        public static string nbColonneNonVide {
            get {
                return ResourceManager.GetString("nbColonneNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ place assise ne doit pas être vide!.
        /// </summary>
        public static string nbPlaceAssiseNonVide {
            get {
                return ResourceManager.GetString("nbPlaceAssiseNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nombre de place payante ne doit pas être vide!.
        /// </summary>
        public static string nbPlacePayanteNonVide {
            get {
                return ResourceManager.GetString("nbPlacePayanteNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ nombre de place minimum ne doit pas être vide!.
        /// </summary>
        public static string nombrePlaceMinNonVide {
            get {
                return ResourceManager.GetString("nombrePlaceMinNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ non chauffeur ne doit pas être vide!.
        /// </summary>
        public static string NonChauffeurNonVide {
            get {
                return ResourceManager.GetString("NonChauffeurNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ numeros de licence ne doit pas être vide!.
        /// </summary>
        public static string numerosLicenceNonVide {
            get {
                return ResourceManager.GetString("numerosLicenceNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ numeros moteur véhicule ne doit pas être vide!.
        /// </summary>
        public static string numMoteurNonVide {
            get {
                return ResourceManager.GetString("numMoteurNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ numeros de série véhicule ne doit pas être vide!.
        /// </summary>
        public static string numSerieNonVide {
            get {
                return ResourceManager.GetString("numSerieNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ poids de bagage maximum ne doit pas être vide!.
        /// </summary>
        public static string poidBagageMaximum {
            get {
                return ResourceManager.GetString("poidBagageMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ Type véhicule ne doit pas être vide!.
        /// </summary>
        public static string typeVehiculeNonVide {
            get {
                return ResourceManager.GetString("typeVehiculeNonVide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le champ zone ne doit pas être vide!.
        /// </summary>
        public static string zoneNonVide {
            get {
                return ResourceManager.GetString("zoneNonVide", resourceCulture);
            }
        }
    }
}
